### PR TITLE
Adding keyboard support for toggling comments

### PR DESCRIPTION
**Pull request by tajayi**
Adding keyboard support for toggling comments using keyboard shortcuts

### CODE REVIEW

**Comment by fallrisk** [comment]
Hello,
Thanks for adding to this project. Did you generate the file "devicetree.tmPreferences" from a "JSON-tmPreferences" file or did you type out that XML?

**Comment by tajayi** [comment]
Mostly copy paste from the syntax reference. I couldn't figure out how to generate it from the JSON file

**Comment by fallrisk** [comment]
I would prefer to have the YAML file because it is more easily maintainable. This would make it easier for other people to expand on it in the future. To make the YAML file look at an example here https://github.com/Benvie/JavaScriptNext.tmLanguage/blob/master/Comments.YAML-tmPreferences. Once you have that file you can compile it into a Plist file (XML Property List file) with the package PackageDev (https://github.com/SublimeText/PackageDev).

**Comment by fallrisk** [comment]
Features added through pull request #3.

**Pull request closed without merging**
